# Generated by Django 5.2.6 on 2025-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HyperPC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_photo', models.ImageField(upload_to='items/')),
                ('item_description', models.TextField()),
            ],
        ),
    ]
