# Generated by Django 5.2.6 on 2025-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('storage', 'Storage'), ('psu', 'PSU'), ('case', 'Case'), ('cooler', 'Cooler'), ('monitor', 'Monitor'), ('accessory', 'Accessory'), ('prebuilt_pc', 'Prebuilt PC'), ('laptop', 'Laptop')], max_length=50),
        ),
    ]
